### PR TITLE
pyAPI

### PR DESCRIPTION
**Pull request by ks156**
Review the existing doc (reorganization; added comments and typo) and added the SPI part

### CODE REVIEW

**Comment by ukicar** [comment]
nice work thanks!

**Comment by drasko** [comment]
Why does  SPILib has to be imported explicitly?
"from weioLib.weioSPI import SPILib" should be included with \* in the previous line, IMHO.

Also, this sucks:
from weioLib.weio import *

We must change weioLib.weio in weioLib.api until it is too late - impact will be in changing all the docs and examples.

**Comment by ks156** [comment]
from weioLib.weio import \* doesn't import weioSPI. To do that, we must import weioSPI via weio.py.

**Comment by drasko** [comment]
Yeap, I know. And this is exactly my point - a note to us all that we must revise API before release. I'm taking a look at it.

**Comment by ks156** [comment]
Ok, let us know your plan to split the tasks. It's a big job since it will cause changes on files included in weioLib, on all examples and on the doc.

**Comment by drasko** [comment]
Noramlly no, just weioLib/weio should be renamed to weioLib/api and all examples should be changed to import this file... I think...

**Pull request merged**
